<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-DEV15" failures="1" tests="8" name="com.saphir.platforme.ActionRunner" time="727.644" errors="0" timestamp="2023-10-13T08:43:46 CEST" skipped="0">
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="81.651"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="90.492"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="120.346"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="98.676"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="100.484"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="94.732"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="70.761"/>
  <system-out/>
  <testcase classname="com.saphir.platforme.ActionRunner" name="runScenario" time="70.502">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.saphir.platforme.moduleAction.stepdefs.FicheActionStepDefinition.Vérifier_les_donnes_de_traçabilite(FicheActionStepDefinition.java:1426)
at ✽.Vérifier les donnes de traçabilite(file:///E:/qualipro/trunk/platforme_test_automation_backend/src/main/java/com/saphir/platforme/features/moduleAction/Action.feature:160)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.saphir.platforme.ActionRunner -->
